SUPABASE_URL = "https://jfuleffsjabisgowwydk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmdWxlZmZzamFiaXNnb3d3eWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMDA0OTMsImV4cCI6MjA3Njg3NjQ5M30.AIWy21xt3nE6JVosKF7YsKkA-5MujsRGvzpttXRvPjY"
